[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200
  force = true

[[redirects]]
  from = "/api/image"
  to = "/.netlify/functions/image"
  status = 200
  force = true

[[redirects]]
  from = "/api/projects"
  to = "/.netlify/functions/projects"
  status = 200
  force = true

[[redirects]]
  from = "/api/stt"
  to = "/.netlify/functions/stt"
  status = 200
  force = true

[[redirects]]
  from = "/api/tts"
  to = "/.netlify/functions/tts"
  status = 200
  force = true

[[redirects]]
  from = "/api/user"
  to = "/.netlify/functions/user"
  status = 200
  force = true

[[redirects]]
  from = "/api/payment"
  to = "/.netlify/functions/payment"
  status = 200
  force = true

[[redirects]]
  from = "/api/payment-status"
  to = "/.netlify/functions/payment-status"
  status = 200
  force = true

[[redirects]]
  from = "/api/payment-callback"
  to = "/.netlify/functions/payment-callback"
  status = 200
  force = true
